version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Keep the default version here if you'd like
    commands:
      - echo "Installing custom Node.js version 16 ..."
      - n --no-preserve 16  # Install Node.js version 16
      - rm -rf /tmp/*  # Clean up temporary files after installation
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Listing current directory contents:"
      - ls -al
      - echo "Running app.js..."
      - node app.js  # Run the app
  post_build:
    commands:
      - echo "Build completed successfully"
      - echo "You should now check the logs to see the app's output."

artifacts:
  files:
    - '**/*'
