version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing custom Node.js version 16 ..."
      - n --no-preserve 16
      - rm -rf /tmp/*
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Listing current directory contents:"
      - ls -al
      - echo "Installing npm dependencies..."
      - npm install
      - echo "Running app.js in the background..."
      - nohup node app.js &  # Run app in background to allow build to continue
  post_build:
    commands:
      - echo "Build completed successfully"
      - echo "You should now check the logs to see the app's output."

artifacts:
  files:
    - '**/*'
